### ISSUE TITLE
stuck on "waiting until udp is ok"

### ISSUE THREAD

**Issue by mathlover3** [char-ptr/gdke#11]
![image](https://github.com/pozm/gdke/assets/121828793/a9bba751-9a17-4f79-b15b-32e8163b7ee0)

**Comment by pozm** [comment]
Hi,

Thanks for making an issue could you provide a binary which you can reproduce this issue for? 

Thanks

**Comment by mathlover3** [comment]
cant send it as that would allow for piritsy but press the playtest button once it happens agien https://store.steampowered.com/app/2737300/Parking_Garage_Rally_Circuit/

**Comment by Gavman69** [comment]
this is happening to me too
seems like something in lib.rs is failing to do shit
![image](https://github.com/pozm/gdke/assets/85568813/e0aa05aa-eda2-45d0-b95c-f07b6544b176)

**Comment by elenakrittik** [comment]
Same thing happening with https://hotcocoastudios.itch.io/quackventure

**Comment by char-ptr** [comment]
> Same thing happening with https://hotcocoastudios.itch.io/quackventure

Thanks for a link to the game, i'll look into this

**Comment by char-ptr** [comment]
> > Same thing happening with https://hotcocoastudios.itch.io/quackventure
> 
> Thanks for a link to the game, i'll look into this

After looking into the game it seems to not be using an encryption key. Although saying this, for me gdre was unable to recover the scripts. It's possible that they used a edited export template or gdre might be out of date.

**Comment by elenakrittik** [comment]
> > > Same thing happening with [hotcocoastudios.itch.io/quackventure](https://hotcocoastudios.itch.io/quackventure)
> > 
> > 
> > Thanks for a link to the game, i'll look into this
> 
> After looking into the game it seems to not be using an encryption key. Although saying this, for me gdre was unable to recover the scripts. It's possible that they used a edited export template or gdre might be out of date.

Interesting, big thanks for trying anyway!

**Comment by mathlover3** [comment]
@char-ptr https://store.steampowered.com/app/2737300/Parking_Garage_Rally_Circuit/ is ready to get requested playtest acsess

**Comment by char-ptr** [comment]
> @char-ptr https://store.steampowered.com/app/2737300/Parking_Garage_Rally_Circuit/ is ready to get requested playtest acsess
unfortunately i'm unable to. it only gives me the option to add to wish list

**Comment by Bingies24** [comment]
The "waiting until udp is ok" issue is because of the .exe being in a directory inside of Program Files (x86) which is protected by Windows. I copied the .exe to gdke's location and got this instead:
![image](https://github.com/char-ptr/gdke/assets/74263388/218f8e0a-c91d-43ef-ac91-27832c9ac0ff)
It's important to mention that is uses a custom build of Godot.
Anyways, here's the .exe file: 
[garagerally.zip](https://github.com/char-ptr/gdke/files/15283725/garagerally.zip)

**Comment by mathlover3** [comment]
> > @char-ptr https://store.steampowered.com/app/2737300/Parking_Garage_Rally_Circuit/ is ready to get requested playtest acsess
> 
> unfortunately i'm unable to. it only gives me the option to add to wish list

yea you were to late

**Comment by char-ptr** [comment]
> The "waiting until udp is ok" issue is because of the .exe being in a directory inside of Program Files (x86) which is protected by Windows. I copied the .exe to gdke's location and got this instead: ![image](https://private-user-images.githubusercontent.com/74263388/329804253-218f8e0a-c91d-43ef-ac91-27832c9ac0ff.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU1OTUwNTgsIm5iZiI6MTcxNTU5NDc1OCwicGF0aCI6Ii83NDI2MzM4OC8zMjk4MDQyNTMtMjE4ZjhlMGEtYzkxZC00M2VmLWFjOTEtMjc4MzJjOWFjMGZmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTEzVDEwMDU1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNhMDdmZmRhMDU1MmVjYjFmMzFmM2FkNzljYjYxNmQ3YWMyZTlmNmZkYjVkNTk3N2Q0OTY2MjU1YmNhZjQyOTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.jUitr3uAh40n6HVMAuVbcap5hDOixZOf9eMJtDt95js) It's important to mention that is uses a custom build of Godot. Anyways, here's the .exe file: [garagerally.zip](https://github.com/char-ptr/gdke/files/15283725/garagerally.zip)

It's possible the error is caused due to steam DRM. if you remove it, it should work i think. (not tested)

**Comment by mathlover3** [comment]
how would we remove steam DRM?

**Comment by elenakrittik** [comment]
> how would we remove steam DRM?
> 

From quick memory, tools like Steamless and Goldberg SteamEmu can help
