### ISSUE TITLE
Printing 62 and a half bytes

### ISSUE THREAD

**Issue by Boberttt** [char-ptr/gdke#12]
![image](https://github.com/char-ptr/gdke/assets/104478197/090b52f3-7678-4011-8828-341d450cf2b6)

**Comment by Boberttt** [comment]
31 and a half*

**Comment by char-ptr** [comment]
That's odd. even if the key was missing a few bytes it should have printed 0 for each missing byte

**Comment by Boberttt** [comment]
well there isn't a byte missing, it's a "nibble"

**Comment by char-ptr** [comment]
anyhow, i'm looking into this. ill let you know with my findings.

**Comment by Boberttt** [comment]
I think I know what the bug is: One byte of the key was 03, but when looking at the printed key there's only "3" (no 0) which breaks things

**Comment by char-ptr** [comment]
Yeah i figured that out. when rewriting i omitted that from the new code base. i have made a new release and it should be fine now

**Comment by Boberttt** [comment]
thank you!

**Comment by Boberttt** [comment]
works!
