### ISSUE TITLE
No load_byte_code

### ISSUE THREAD

**Issue by olvior** [char-ptr/gdke#14]
I have disassembled an encrypted executable made in Godot 4.2.2, and there does not seem to be a "load_byte_code" string in the file. 
![image](https://github.com/char-ptr/gdke/assets/78297864/82cab064-bc06-4240-84ca-b12891b9539e)

**Comment by olvior** [comment]
I have found other strings that can be used, such as "Can't open encrypted pack-referenced file '"

**Comment by char-ptr** [comment]
Since they changed it in 4.0 you need to search for something else instead. it should be something like `FileAccessEncrypted::open_and_parse`
