### ISSUE TITLE
doesnt load a single thing on my pc

### ISSUE THREAD

**Issue by jmxamongusmodder** [char-ptr/gdke#15]
doesnt load a single thing on my pc

tried using the exe the thingie came with, nothin, it just closes .1 miliseconds after running.

WHAT DO I DO?!??!

**Comment by thatcupcakefactorie** [comment]
it's because you're supposed to drag the exe of whatever you are trying to get the encryption key for, on the gdke.exe
if you hover over it, it should say `open with 'gdke.exe'`

**Comment by char-ptr** [comment]
Application is now bundled with gui
