### ISSUE TITLE
Cannot use GUI

### ISSUE THREAD

**Issue by HundSimon** [char-ptr/gdke#17]
when trying to execute this program, it says 
```
thread 'main' panicked at src/main.rs:6:55:
called `Option::unwrap()` on a `None` value
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
hope this information helps
i am using the latest release

**Comment by PaologGithub** [comment]
I tried putting a Godot Instance onto the directory, and putting it as arguments, and the program didn't failed, but didn't get the key

**Comment by HundSimon** [comment]
Isn't this a gui program? Why it only works with argument?

**Comment by PaologGithub** [comment]
> Isn't this a gui program? Why it only works with argument?

On release 0.2.0, char-ptr rewrote everything, and deleted the UI. On release 0.2.2, he said "Last release before UI", so normally release 0.2.3 will have UI

**Comment by HundSimon** [comment]
ok, thanks
