### ISSUE TITLE
Not starting

### ISSUE THREAD

**Issue by Shmoopey** [char-ptr/gdke#20]
Any solutions to a cmd flashing and closing without actually starting anything?

**Comment by PaologGithub** [comment]
> Any solutions to a cmd flashing and closing without actually starting anything?

I think it is because it crashes. Try opening CMD at current folder, and then do `gdke Drive:/Path/To/Exe`.

If it continues crashing, then you'll have the error. If it doesn't crash, then it means that you didn't put any file

**Comment by char-ptr** [comment]
there is now a gui bundled with the application
