### ISSUE TITLE
linux build?

### ISSUE THREAD

**Issue by beatrixwashere** [char-ptr/gdke#3]
would it be possible to build this for linux on my computer? i'm not sure which rust scripts to compile and which dependencies to install. thanks!

**Comment by pozm** [comment]
Sorry, at the moment the library which i maintain [(poggers)](https://github.com/pozm/poggers) which does the heavy lifting for memory operations doesn't support linux. although im looking at improving parity in the future, just right now it's windows only.

**Comment by thequeenbea** [comment]
i tried compiling one of the scripts before i opened this issue and it threw an error related to that; thanks for responding!

**Comment by char-ptr** [comment]
no longer possible at the moment due to change of methods.. unless someone wants to rewrite in linux
