### ISSUE TITLE
does the decryption support multiple godot versions?

### ISSUE THREAD

**Issue by thecodemonkey-sudo** [char-ptr/gdke#8]
Hello, I am trying to decode a Godot 3.5.3 (Steam Edition) game. However, I could not get your software to work. Looking through the godot engine code, it seems that godot uses different encryption types for different versions. (ex: aes cbc vs aes ebc). Is this accounted for in the code?

**Comment by pozm** [comment]
All the versions use the same way to store the encryption key. so it doesn't matter what it is or if they change it as long as how the key is embedded remains the same (which i believe has not changed yet). also realistically you'd want to fork this and add your own signature for it to scan for in the src (or just find it through reverse engineering) until i figure out a way to make it consistently work between versions
